### ISSUE TITLE
Please add to README.md on how to use this beast

### ISSUE THREAD

**Issue by yarikoptic** [neurdylab/physai#2]

**Comment by rgbayrak** [comment]
Certainly! Added a brief info to the README to get the ball rolling. 

@yarikoptic Could you elaborate on your suggestion? Are you thinking of a brief guide to help navigate through the different sections of our website and understand how to interact with each tab?

**Comment by yarikoptic** [comment]
not even that -- just to describe 
- what it is (website)
- where to find it (if there is public url) or how to deploy it (if it is a thing people should deploy for themselves with some customizations)

May be one or two main webshots just to hint on what is there but not really mandatory if there is a public URL.

ATM it is not clear what this thing is really and what to do with it.

**Comment by rgbayrak** [comment]
@yarikoptic Improved [README](https://github.com/neurdylab/physai), closing this issue.
